esphome:
  name: washer

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
ota:
  - platform: esphome

external_components:
  - source:
      type: local
      path: components
    components: [ adxl345 ]

i2c:
  sda: GPIO6
  scl: GPIO7
  frequency: 400kHz
  scan: true      # logs "Found i2c device at 0x53" on boot

adxl345:
  - id: accel
    address: 0x53
    update_interval: 500ms
    range: 4G
    jitter:
      id: jitter
      name: "Jitter"

sensor:
  platform: template
  id: smoothed_jitter
  name: "Smoothed Jitter"
  lambda: "return id(jitter).state;"
  update_interval: 1s
  state_class: measurement
  unit_of_measurement: "m/s²"
  filters:
    - sliding_window_moving_average:
        window_size: 60
        send_every: 5

binary_sensor:
  - platform: template
    name: "Running"
    id: dryer_running
    publish_initial_state: true
    lambda: |-
      return id(smoothed_jitter).state > id(jitter_threshold).state;
    filters:
      - delayed_off: 20min

number:
  - platform: template
    name: "Jitter Threshold"
    id: jitter_threshold
    optimistic: true
    min_value: 10
    max_value: 40
    step: 0.5
    initial_value: 13
    restore_value: true
